platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'SwiftNews' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'RxAlamofire'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts target.name
    end
end
